POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Pena",
  "username": "pena100",
  "password": "password",
  "email": "p.ena@mail.com",
  "role": "admin"
}

### Post login
POST http://localhost:3000/api/v1/auth/login
content-type: application/json

{
  "username": "pena100",
  "password": "password"
}